### ISSUE TITLE
Mobile view improvement

### ISSUE THREAD

**Issue by djkunedo** [pixelnest/presskit.html#4]
Hi guys. First of all, thanks for presskit.html. It's a great tool, but I think that it could be even better if you could make some improvements on the mobile view. Have you planned to release an update with a responsive and fixed top navigation bar or at least trying to locate the header above or inside the nav tag?

**Comment by solarsailer** [comment]
Hello,

It's already responsive.
A fixed navigation bar would be weird and take too much space, imo. 🤔

Do you have a quick mockup of what you imagine?

Thanks. :)

**Comment by djkunedo** [comment]
Hi solarsailer,

Yeah it's already responsive, what I meant it's that you could add the navbar so it appears only on mobile resolutions but we would keep using the original look for desktop devices.

I'll try to give you further details about what I have in mind. This is how it currently looks on mobile:
![currentview](https://user-images.githubusercontent.com/6534378/34718006-59e709d8-f535-11e7-9dcf-60a2ed04060b.jpeg)
I think that the header imager could look better above Pixelnest Studio or below pixelnest.io, imo.

The navbar I have in mind it would be something like this: https://themeisle.com/demo/?theme=Zerif%20Lite (you have to select the mobile view on the top of the web to see the navbar with the hamburger menu buttom). I don't think that this navbar takes too much space, but you could comment the code to fix the navbar and let the users decide to fix it or not if you don't want to fix it by default. If you finally implement the navbar, I guess that the header image would look good below the navbar.

Thanks to you ;)

**Comment by solarsailer** [comment]
Thanks for the detail.

That's what I thought. We tried to stay true to the original presskit(), but I think it might be better this way, indeed.

I'll look into that if I have some time before the week-end. ;)

Cheers.

**Comment by solarsailer** [comment]
Hello,

I finally added a way to have an hamburger menu (along other features): https://github.com/pixelnest/presskit.html/releases/tag/0.7.0

Run with `presskit build -M` and it should be good. ;)

(Don't forget the flag, the hamburger behavior is opt-in, not by default)

- For the fixed menu, I'm not convinced right now.
- For the header above the title, it's a bit more complicated since I need to rework the structure and I don't want to diverge too much from the original presskit layout.

Cheers!
